# ローカル開発用
version: "3.5"

services:
  db:
    image: postgres:latest
    container_name: "appdb"
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    env_file: .env
    environment:
      - API_VERSION=development
      - CLEARDB_DATABASE_URL=postgres://root:password@appdb:5432/sora?sslmode=disable
    ports:
      - 7777:7777
    depends_on:
      - db