# ローカル開発用
version: "3.5"

services:
  db:
    image: postgres:latest
    container_name: "appdb"
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      target: builder
    env_file: .env
    environment:
      - API_VERSION=development
    ports:
      - 7777:7777
    volumes: 
      - .:/app
    command: "air"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db